# set this if not already set
# generates additional files
# CXXFLAGS ?= -g -Wall -Werror -Wextra

step0_repl: step0_repl.cpp
# CXX is the c++ compiler 
	clang++ $(CXXFLAGS) -std=c++11 -o step0_repl step0_repl.cpp

clean:
	rm -rf step0_repl