# set this if not already set
CXXFLAGS ?= -g -Wall -Werror -Wextra

step0_repl: step0_repl.cpp
# CXX is the c++ compiler 
	$(CXX) $(CXXFLAGS) -o step0_repl step0_repl.cpp

clean:
	rm -rf step0_repl step0_repl.dSYM